services:
  app:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cashcow
    container_name: cashcow-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - cashcow

  db:
    image: mysql:8.0
    container_name: cashcow-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - cashcow
  nginx:
    image: nginx:1.17-alpine
    container_name: cashcow-nginix
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - cashcow

networks:
  cashcow:
    driver: bridge

